name: Publish Library

on:
  release:
    types: [created]

jobs:
  prepare-v17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i
      - run: node_modules/.bin/nx run ng-utils:build
      - run: cd ./dist/libs/ng-utils && npm version 17${{github.ref_name}} --no-git-tag-version
      - uses: actions/upload-artifact@v3
        with:
          name: package-v17
          path: dist/libs/ng-utils/

  publish:
    runs-on: ubuntu-latest
    needs: [prepare-v17]
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish Version 17
        run: cd ./package-v17 && npm publish --tag v17-lts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Add Latest Tag to v17
        run: cd ./package-v17 && npm dist-tag add @thalesrc/ng-utils@$(perl -ne 'print "$1" if /"version":\s?"(.*?)"/' ./package.json) latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
